// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package repos

import (
	"context"

	"github.com/google/uuid"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (user_id, title)
VALUES ($1, $2)
RETURNING id, user_id, title, done, created_at, updated_at
`

type CreateTodoParams struct {
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo, arg.UserID, arg.Title)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos WHERE id = $1 AND user_id = $2
`

type DeleteTodoParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTodo(ctx context.Context, arg DeleteTodoParams) error {
	_, err := q.db.Exec(ctx, deleteTodo, arg.ID, arg.UserID)
	return err
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, user_id, title, done, created_at, updated_at FROM todos WHERE id = $1 AND user_id = $2
`

type GetTodoByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTodoByID(ctx context.Context, arg GetTodoByIDParams) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodoByID, arg.ID, arg.UserID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTodosByUser = `-- name: ListTodosByUser :many
SELECT id, user_id, title, done, created_at, updated_at FROM todos WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTodosByUser(ctx context.Context, userID uuid.UUID) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodosByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Done,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET title = $2, done = $3, updated_at = NOW()
WHERE id = $1 AND user_id = $4
RETURNING id, user_id, title, done, created_at, updated_at
`

type UpdateTodoParams struct {
	ID     uuid.UUID `json:"id"`
	Title  string    `json:"title"`
	Done   bool      `json:"done"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.ID,
		arg.Title,
		arg.Done,
		arg.UserID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
